### ISSUE TITLE
NvFBC

### ISSUE THREAD

**Issue by UltraShadoww** [MasterFighterr/passthru-hooks-example#1]
Hello! Thank you for your tutorial, I was able to configure my VM with looking glass successfully. The only problem is, I have a consumer card so I can’t use NvFBC. Please help me configure my VM so I can bypass the limitation like you did.

Thank You!

**Comment by MasterFighterr** [comment]
What issue are you having exactly? Are you getting an error message? NvFBC works on consumer cards, the card I'm using is a 1080 Ti.
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Mar 25, 2023, 16:10 by ***@***.***:

**Comment by UltraShadoww** [comment]
The looking glass wiki says : “NvFBC is only supported on professional-grade GPUs, and will not function on consumer-grade cards like those from the GeForce series.”

https://looking-glass.io/docs/B6/faq/

NvFBR doesn’t work out of the box on consumer cards. Certain workarounds need to be made for it to work. I’m surprised your 1080ti is working without any such workarounds. For me, when I enable NvFBC, looking glass doesn’t work, and doesn’t get any video output.

**Comment by MasterFighterr** [comment]
What card are you using? By chance did you make the looking-glass-host.ini file already? The only things I can think besides those two is did you install the KVMFR kernel module from looking-glass-source?
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Mar 25, 2023, 17:08 by ***@***.***:

**Comment by UltraShadoww** [comment]
I’m on a 1050ti, I’ve made the INI and installed the kernel module, everything works except when I use NvFBC.

**Comment by MasterFighterr** [comment]
This might not be a problem with NvFBC directly. On my machines, I have to connect with QXL and then remove QXL again for it to work, try doing that and see if it turns your luck around.
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Mar 25, 2023, 17:40 by ***@***.***:

**Comment by UltraShadoww** [comment]
Thank you for the input, i’ve switched over to DX12, which is much smoother (even smoother than NvFBC) by installing the looking-glass bleeding edge packages.

**Comment by MasterFighterr** [comment]
No problem, that's an odd solution though. Honestly with DMABUF you may not even really need NvFBC anyways because DMABUF is pretty much equivalent to bare metal but it might help with higher refresh rates.
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Mar 25, 2023, 19:00 by ***@***.***:
