### ISSUE TITLE
looking glass stays black

### ISSUE THREAD

**Issue by oskool** [MasterFighterr/passthru-hooks-example#2]
Hi,

first of all thanks for the tutorial and sorry for my English. 
I hope you understand it. :)

Except that I get no image of Windows when I run spice, everything worked great.

As soon as I connect a dongle, I get a picture of Windows when I run spice.

If I delete the below

   `<qemu:arg value="-device"/>`
   `<qemu:arg value="ivshmem-plain,id=shmem0,memdev=looking-glass"/>`
    `<qemu:arg value="-object"/>`
    `<qemu:arg value="memory-backend-file,id=looking-glass,mem-path=/dev/kvmfr0,size=128M,share=yes"/>`

and set video back to qxl and run spice, I get a picture of Windows, but looking-glass crashes. This is normal since I deleted the code above. at least I think.

Do you have any idea what I can do to get it to run?

Thanks a lot

**Comment by MasterFighterr** [comment]
Your GPU may not support NVFBC (supported on enterprise cards and a select number of consumer cards), try removing it from your looking-glass config inside of the VM. With DMABUF, the performance hit without NVFBC will not be noticeable for most people.

**Comment by oskool** [comment]
Thanks for the answer, but unfortunately I do not understand what I should change now. My GPU is a 3060ti.

On the Internet I can not really find anything about it, or I'm looking wrong. Would you have a link where I can read about it?

One thing I should mention, with these steps it worked once, 

[https://github.com/VGPU-Community-Drivers/NvFBC-Unlock](url)

but I don't know what I did. I just do not manage to restore this one state.

**Comment by MasterFighterr** [comment]
Remove the NVFBC line from looking-glass.ini inside the windows vm

**Comment by MasterFighterr** [comment]
Note that I do not run the workaround and do not recommend them because they are not reliable. If you do, keep in mind I will not be able to provide much if any support

**Comment by oskool** [comment]
Sorry it took a little longer.
If I just delete nvfbc, it makes no difference.
I've now entered this dxgi in the looking-glass-host.ini instead of nvfbc, now it works.

Or did you mean another solution?
